-- product-service schema. Matches com.ecommerce.productservice.entity.Product.
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    price_cents BIGINT NOT NULL,
    sku         VARCHAR(255) NOT NULL UNIQUE
);
